# Generated by Django 4.1.1 on 2024-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_clientmessage_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientMessage',
            new_name='HelpMessage',
        ),
        migrations.RenameField(
            model_name='helpmessage',
            old_name='message_content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='f06f8413', max_length=8, unique=True),
        ),
    ]
